project_structure:
  build: build
  contracts: contracts
  interfaces: interfaces
  reports: reports
  scripts: scripts
  tests: tests

networks:
  default: development
  development:
    gas_limit: max
    gas_buffer: 1
    gas_price: 0
    max_fee: null
    priority_fee: null
    reverting_tx_gas_limit: max
    default_contract_owner: true
    cmd_settings:
      accounts: 100
      default_balance: "10000 ether"
      # port: 8545
      # gas_limit: 6721975
      # accounts: 100
      # chain_id: 1337
      # network_id: 1588949648
      # evm_version: istanbul
      # fork: null
      # disable_cache: null
      # mnemonic: brownie
      # block_time: 0
      # default_balance: 1000
      # # time: 2020-05-08T14:54:08+0000
      # unlock: null

  live:
    gas_limit: auto
    gas_buffer: 1.1
    gas_price: auto
    max_fee: null
    priority_fee: null
    reverting_tx_gas_limit: false
    default_contract_owner: false

compiler:
  evm_version: null
  solc:
    version: null
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0"
      # - "@openzeppelin=OpenZeppelin/openzeppelin-contracts-upgradeable@4.7.2"
      - "@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.0"
      - "@gnosis.pm/safe-contracts=safe-global/safe-contracts@1.3.0"
      - "@uniswap/v2-periphery=Uniswap/v2-periphery@1.0.0-beta.0"
      - "@uniswap/v2-core=Uniswap/v2-core@1.0.1"
  vyper:
    version: null

console:
  show_colors: true
  color_style: monokai
  auto_suggest: true
  completions: true
  editing_mode: emacs

reports:
  exclude_paths: null
  exclude_contracts: null
  only_include_project: true

hypothesis:
  deadline: null
  max_examples: 50
  report_multiple_bugs: False
  stateful_step_count: 10
  phases:
    explicit: true
    reuse: true
    generate: true
    target: true
    shrink: true

autofetch_sources: false
dependencies: null
dev_deployment_artifacts: false
